pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Install dependencies and build the application
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }

        stage('Unit Test') {
            steps {
                script {
                    // Run unit tests
                    sh 'npm run test'
                }
            }
        }

        stage('Integration Test') {
            steps {
                script {
                    // Run integration tests
                    sh 'npm run test:e2e'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded! You can add additional steps or notifications here.'
        }
        failure {
            echo 'Pipeline failed! You can add additional steps or notifications here.'
        }
    }
}
